### ISSUE TITLE
mkdir needs quotation

### ISSUE THREAD

**Issue by stas2z** [rthomas67/thingiverse_add_dl_all_script_generator#1]
im too lazy to make a p/r)
when you call mkdir with smth like awesome-thing-(v2)-lite it will cause an error
so you need to call it mkdir 'awesome-thing-(v2)-lite'

**Comment by rthomas67** [comment]
Fixed.  Thanks for the feedback.
https://github.com/rthomas67/thingiverse_add_dl_all_script_generator/commit/693f53c49416e906ac4df8419996018f5ae943c8
